version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres_desafio_thera
    environment:
      POSTGRES_USER: thera_user
      POSTGRES_PASSWORD: thera_password
      POSTGRES_DB: postgres_thera
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_desafio_thera
    environment:
      DATABASE_URL: postgres://thera_user:thera_password@postgres:5432/postgres_thera
      SERVER_PORT: 3000
      JWT_HASH_MD5: 5ef41c09829700e022099de37b96bff8
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - app_network
    command: >
      sh -c " npx prisma migrate deploy && node dist/src/main.js "

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
